
exception-handle:
  project-name: com.lihang.exception.client
  email:
    from: ceshi@163.com
    to:
      - ceshi@139.com
spring:
  mail:
    host: smtp.163.com
    port: 25
    password: ceshi123456
    username: ceshi@163.com